
data = [
    ['Ahnlab Safe Transaction', 'astxdn.exe', 'https://bank.shinhan.com/sw/astx/astxdn.exe'],
    ['Adobe Acrobat Reader', 'readerdc64_ga_cra_install.exe', 'https://admdownload.adobe.com/rdcm/installers/live/readerdc64_ga_cra_install.exe'],
    ['Adobe Creative Cloud', 'Creative_Cloud_Set-Up.exe', 'https://prod-rel-ffc-ccm.oobesaas.adobe.com/adobe-ffc-external/core/v1/wam/download?sapCode=KCCC&productName=Creative%20Cloud&os=win&guid=d8738952-724a-4ffa-b844-ae8af08d8259&contextParams=%7B%22component%22%3A%22cc-home%22%2C%22visitor_guid%22%3A%2217544139162251472000750151510417531777%22%2C%22campaign_id%22%3A%2245274%7C92568%7C96659%7C2021-10-cme-1%7C2023-09-apps-catalog-M2%22%2C%22browser%22%3A%22chrome%22%2C%22context_guid%22%3A%227d3c1f19-9cdc-4e58-92fc-6c0f2350c3bd%22%2C%22variation_id%22%3A%22130841%3A45274%7C287164%3A92568%7C299138%3A96659%7Ctest%3A2021-10-cme-1%7Ctest%3A2023-09-apps-catalog-M2%22%2C%22experience_id%22%3A%22na%3A45274%7Cna%3A92568%7Cna%3A96659%7Cna%3A2021-10-cme-1%7Cna%3A2023-09-apps-catalog-M2%22%2C%22planCodeList%22%3A%22cc_free%7Cdc_free%22%2C%22updateCCD%22%3A%22true%22%2C%22secondarySapcodeList%22%3A%22%22%2C%22Product_ID_Promoted%22%3A%22KCCC%22%2C%22userGuid%22%3A%22198278505EBCAAC20A495FB4%40AdobeID%22%2C%22authId%22%3A%22198278505EBCAAC20A495FB4%40AdobeID%22%2C%22contextComName%22%3A%22Organic%3ACCH%22%2C%22contextSvcName%22%3A%22NO-CCD%22%2C%22contextOrigin%22%3A%22Organic%3ACCH%22%2C%22AMCV_D6FAAFAD54CA9F560A4C98A5%2540AdobeOrg%22%3A%22-637568504%257CMCIDTS%257C20144%257CMCMID%257C17544139162251472000750151510417531777%257CMCAAMLH-1741061086%257C3%257CMCAAMB-1741061086%257C6G1ynYcLPuiQxYZrsz_pkqfLG9yMXBpb2zX5dvJdYQJzPXImdj0y%257CMCOPTOUT-1740463486s%257CNONE%257CMCSYNCSOP%257C411-20147%257CvVersion%257C5.1.1%22%2C%22mid%22%3A%2222233660565938630591820048530096679807%22%2C%22aid%22%3A%22%22%2C%22AppMeasurementVersion%22%3A%222.23.0%22%2C%22kaizenTrialDuration%22%3A7%7D&wamFeature=nuj-live&environment=prod&api_key=CCHomeWeb1'],
    ['Alcapture', 'https://advert.estsoft.com/?event=201110311523647', 'https://creativecloud.adobe.com/apps/download/creative-cloud'],
    ['APS Engine', 'APS_Engine.exe', 'https://mybank.ibk.co.kr/IBK/uib/sw/yettiesoft/APS/APS_Engine.exe'],
    ['CrossWeb EX', 'INIS_EX_SHA2.exe', 'https://bank.shinhan.com/sw/initech/extension/down/INIS_EX_SHA2.exe?ver=1.0.1.961'],
    ['Wizin Delfino G3', 'delfino-g3-sha2.exe', 'https://mybank.ibk.co.kr/IBK/uib/sw/wizvera/delfino/down/delfino-g3-sha2.exe'],
    ['IPinsideLWS', 'I3GSvcManager.exe', 'https://mybank.ibk.co.kr/IBK/uib/sw/interezen/agent/I3GSvcManager.exe'],
    ['Printmade', 'Printmade3_setup.exe', 'https://bank.shinhan.com/sw/printmade/download_files/Windows/Printmade3_setup.exe'],
    ['TouchEnNxKey', 'TouchEn_nxKey_32bit.exe', 'https://bank.shinhan.com/sw/raon/TouchEn/nxKey/module/TouchEn_nxKey_32bit.exe?ver=1.0.0.8'],
    ['Bandizip', 'BANDIZIP-SETUP-STD-X64.EXE', 'https://kr.bandisoft.com/bandizip/dl.php?web'],
    ['Gom Audio', 'GOMAUDIOGLOBALSETUP_NEW.EXE', 'https://cdn2.gomlab.com/gretech/audio/GOMAUDIOGLOBALSETUP_NEW.EXE'],
    ['Alsong', 'ALSong352.exe', 'https://advert.estsoft.com/?event=200803271705239'],
    ['Melon Player', 'MelonSetup.exe', 'https://cdnstatic.melon.co.kr/svc/pcp/apps/w10/MelonSetup.exe'],
    ['Dropbox', 'DropboxInstaller.exe', 'https://dl-web.dropbox.com/installer?arch=x86_64&authenticode_sign=True&build_no=218.4.4348&juno=True&juno_use_program_files=True&omaha=True&omaha_use_program_files=True&plat=win&tag=eyJUQUdTIjoiZUp5clZpcE9MUzdPek0tTHoweFJzbEl3TlRFeE1qSXl0ekN4TkRNM05UQTB0REEwTVRJek1EUTFNalcyTkRRMU1ESTBOTFUwTnFvRkFKc1VEWFV-QE1FVEEifQ&tag_token=AgSUCkxdvsAaMv3mTcZhPII-gCEHcXYf7IqCPIGb8yzwdA'],
    ['Evernote', 'Evernote-latest.exe', 'https://win.desktop.evernote.com/builds/Evernote-latest.exe'],
    ['Google Drive', 'GoogleDriveSetup.exe', 'https://dl.google.com/drive-file-stream/GoogleDriveSetup.exe'],
    ['OneDrive', 'OneDriveSetup.exe', 'https://go.microsoft.com/fwlink/p/?LinkID=2182910&clcid=0x412&culture=ko-kr&country=kr'],
    ['EA app', 'EAappInstaller.exe', 'https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EAappInstaller.exe'],
    ['Battlenet', 'Battle.net-Setup.exe', 'https://www.blizzard.com/download/confirmation?product=bnetdesk'],
    ['Albion online', 'albion-online-setup.exe', 'https://live.albiononline.com/clients/20250214110215/albion-online-setup.exe'],
    ['nProtect Online Security', 'nos_setup.exe', 'https://supdate.nprotect.net/nprotect/nos_service/windows/install/nos_setup.exe'],
    ['Purple', 'PurpleInstaller_2_25_212_6.exe', 'https://gs-purple-inst.download.ncupdate.com/Purple/PurpleInstaller_2_25_212_6.exe'],
    ['Genshin Impact', 'GenshinImpact_install_ua_3f1192c7d78b.exe', 'https://sg-public-api.hoyoverse.com/event/download_porter/trace/ys_global/genshinimpactpc/default?url=https%3A%2F%2Fgenshin.hoyoverse.com%2Fko%2Fhome&appid=525'],
    ['GOOSE GOOSE DUCK', 'Goose Goose Duck Installer 3.14.01 release.exe', 'https://gaggle.fun/goose-goose-duck'],
    ['PorkerStarts', 'PokerStarsInstall.exe', 'https://download.pokerstars.com/poker/client/download/'],
    ['Rocket_League', 'EpicInstaller-18.0.0.msi', 'https://launcher-public-service-prod06.ol.epicgames.com/launcher/api/installer/download/EpicGamesLauncherInstaller.msi'],
    ['World of Tanks', 'world_of_tanks_install_asia_d7xwpwyusv1x.exe', 'https://redirect.wargaming.net/WoT/latest_web_install_asia'],
    ['World of Warships', 'world_of_warships_ww_install_asia_d7xwxhtjontu.exe', 'https://wds.wargaming.net/wgc/releases_tTrHgLCKHBRiaL/wgc_24.08.02.8277_asia/world_of_warships_ww_install_asia.exe?sid=SIDHqNAIQCeD_VPqE14lFlbFSTvTeDty7bOXWfcS-MJAsFvu_d8W7m-if8zOjqqofNxS14iJ2Kmy6OUV1qmlgfZXVmajwBtkVJAoP2GXHJ4gsYiqfX2POOtRNfIWHcHO662ZZoNqFJa3d_Ylg&enctid=d7xwxhtjontu&lpsn=WoWs+direct+WGC+download+ASIA&foris=1&teclient=1740119043985793231&utm_source=wg_web_site&utm_medium=organic&utm_campaign=y3dwj24l&utm_content=unknown'],
    ['Autodesk Access', 'AdAccess-installer.exe', 'https://emsfs.autodesk.com/utility/access/1/installer/latest/AdAccess-installer.exe'],
    ['PDFCreator', 'PDFCreator-5_3_3-Setup.exe', 'https://www.pdfforge.org/pdfcreator/download'],
    ['Polaris Office', 'PolarisOfficeSetup.exe', 'https://www.polarisoffice.com/en/download'],
    ['Alpdf', 'ALPDF403.exe', 'https://altools.co.kr/product/ALPDF'],
    ['Blitz', 'Blitz-2.1.275.exe','https://blitz.gg/download/win'],
    ['Riot Games', 'Install League of Legends sg2.exe', 'https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.sg2.exe'],
    ['Wondershare pdfelement', 'pdfelement-pro_setup_full5239.exe', 'https://download.wondershare.com/pdfelement-pro_full5239.exe?_gl=1*15dl66l*_ga*OTQ2NTk5MDE3LjE3NDAzNjE2MzQ.*_ga_24WTSJBD5B*MTc0MDM2MTYzMy4xLjAuMTc0MDM2MTYzNS42MC4wLjE2NDIwNDk4NQ..*_gcl_au*MTc0MTcxMjM3MC4xNzQwMzYxNjM2'],
    ['PDF-XChange Editor', 'PDFXVE10.exe',"https://www.pdf-xchange.de/DL/tracker10/editor-zip-tracker.php"],
    ['BANDIVIEW', 'BANDIVIEW-SETUP-X64.EXE', 'https://www.bandisoft.com/bandiview/dl.php?web'],
    ['AlSee', 'ALToolsSetup.exe', 'https://advert.estsoft.com/?event=200910145916818'],
    # ['DWG FastView', 'DWGFastView(KR-1)_x64_1.exe', 'https://dwgfastview-bsyun.dwgfastview.com/Download/KR/8.8/DWGFastView%28KR-1%29_x64_1.exe'],
    ['Alcapture', 'ALCapture318.exe', 'https://advert.estsoft.com/?event=201110311523647'],
    ['GOM Cam', 'GOMCAM2024SETUP_NEW.EXE', 'https://cdn2.gomlab.com/gretech/gomcam/GOMCAM2024SETUP_NEW.EXE'],
    ['oCam','oCam_v550.0.exe','https://ohsoft.net/update/download.php'],
    ['Ahnlab V3 Lite','V3_Lite_Setup.exe','https://provide.ahnlab.com/v3lite/v40/download/V3_Lite_Setup.exe'],
    ['CCleaner','ccsetup633.exe','https://www.ccleaner.com/ccleaner/download/standard'],
    ['Alyac','ALYac25.exe','https://cdn1.estsecurity.com/setup/ALYac/ALYac25.exe'],
    ['GOM Player Plus', 'GOMPLAYERPLUS2024SETUP_NEW.EXE','https://cdn2.gomlab.com/gretech/gomplayerplus/GOMPLAYERPLUS2024SETUP_NEW.EXE'],
    ['KMPlayer', 'KMPlayer_4.2.3.21.exe', 'https://www.kmplayer.com/home#layer-pc'],
    ['KMPlayer 64X', 'KMP64_2025.1.21.12.exe', 'https://www.kmplayer.com/home#layer-pc'],
    ['Kollus Player', 'KollusAgent-3.1.1.1.r5.exe', 'https://v.kr.kollus.com/pc_player_install/agent?cpk=megastudyedu'],
    ['PotPlayer', 'PotPlayerSetup64.exe', 'https://t1.kakaocdn.net/potplayer/PotPlayer/Version/Latest/PotPlayerSetup64.exe'],
    ['VLC Media Player', 'vlc-3.0.21-win64.exe', 'https://www.videolan.org/vlc/'],
    ['Prime Video', 'Prime Video for Windows Installer.exe', 'https://get.microsoft.com/installer/download/9P6RC76MSMMJ?hl=en-us&gl=en&referrer=storeforweb&ocid=sfw-fab-control'],
    ['LINE', 'LineInst.exe', 'https://desktop.line-scdn.net/win/new/LineInst.exe'],
    ['Zoom', 'ZoomInstallerFull.exe', 'https://zoom.us/download'],
    ['DuckDuckGo Browser', 'DuckDuckGo.appinstaller', 'https://duckduckgo.com/windows'],
    ['Opera', 'OperaSetup.exe', 'https://www.opera.com/computer/thanks?ni=stable&os=windows'],
    ['Vivaldi', 'Vivaldi.7.1.3570.58.x64.exe', 'https://vivaldi.com'],
    ['Whale', 'WhaleSetup.exe', 'https://installer-whale.pstatic.net/downloads/installers/WhaleSetup.exe'],
    ['GoToMeeting', 'GoToMeeting Opener.exe', 'https://meet.servers.getgo.com/opener/e30.eyJpYXQiOjE3NDA5NzgzMDQsImxhdW5jaFBhcmFtcyI6eyJidWlsZCI6IjE5OTUwIiwidGVsZW1ldHJ5VVJMIjoiaHR0cHM6Ly9sYXVuY2hzdGF0dXMuZ2V0Z28uY29tL2xhdW5jaGVyMi90ZWxlbWV0cnkvaGVscGVyP3Rva2VuPWcybS1yOXFpdnB1ZjVzcnN5dWIxeWRya2pnLWIxOTk1MC1zY2xzSW5zdGFsbF82ODQwNWJkZV9hZjU5XzQxNDZfODgyYV8xNDI2YjU2NzljZjQiLCJlbmRwb2ludFBhcmFtcyI6eyJQcm9kdWN0IjoiZzJtIiwic2Vzc2lvblRyYWNraW5nSWQiOiJjbHNJbnN0YWxsLTY4NDA1YmRlLWFmNTktNDE0Ni04ODJhLTE0MjZiNTY3OWNmNCIsImxhdW5jaFVybCI6Im1lZXRpbmc_c2Vzc2lvblRyYWNraW5nSWQ9Y2xzSW5zdGFsbC02ODQwNWJkZS1hZjU5LTQxNDYtODgyYS0xNDI2YjU2NzljZjQmY2xpZW50R2VuZXJhdGlvbj1yb2xsaW5nIiwiZW52IjoibGl2ZSJ9fSwidmVyc2lvbiI6IjEuMCIsImZsb3dUeXBlIjoiaW5zdGFsbCIsImVuZHBvaW50Rmxhdm9yIjp7ImZsYXZvciI6Im5ldXRyb24iLCJmbGF2b3JFbmZvcmNlZCI6InRydWUifSwiaXNGbGF2b3JGaW5hbCI6dHJ1ZX0.e30'],
    ['Wave', 'Wave Browser.exe', 'https://wavebrowser.com/'],
    ['QQ', 'QQ_9.9.17_250110_x64_01.exe', 'https://im.qq.com/pcqq/index.shtml'],
    ['TeamViewer', 'TeamViewer_Setup_x64.exe', 'https://dl.teamviewer.com/download/version_15x/TeamViewer_Setup_x64.exe?src=cookie-banner&ref=https%3A%2F%2Fwww.teamviewer.com%2Fvi%2F'],
    ['Telegram', 'tsetup-x64.5.11.1.exe', 'https://telegram.org/dl/desktop/win64'],
    ['UCWorks', 'UC_Works_setup.exe', 'https://update.ucwaremobile.com/ucportal/UC_Works_setup.exe'],
    ['WeChat', 'WeChatSetup.exe', 'https://dldir1v6.qq.com/weixin/Windows/WeChatSetup.exe'],
    ['Clip Studio', 'CSP_323w_setup.exe', 'https://www.clipstudio.net/en/purchase/complete_win/'],
    ['FL Studio', 'flstudio_win64_24.2.2.4597.exe', 'https://support.image-line.com/redirect/flstudio_win_installer?_gl=1*g4ilmg*_gcl_au*NTcxNjY4OTM3LjE3NDA5OTQ1NTg.'],
    ['Photoscape', 'PhotoScape 3.4.exe', 'https://www.filehorse.com/download/file/sEqp0V5z8oWNsJ9_ZMWSa0uvz5zCCgScHGgKjT_TVv4Krm0BoXah6S7b5zDNxQIBIEg4qnkBxdjdSMC1ZGjR4Q/'],
    ['Vegas Pro', 'trial_vegaspro22_dlm_je96k4.exe', 'https://dl03.vegascreativesoftware.com/trial_vegaspro22_dlm_je96k4.exe'],
    ['Wondershare', 'filmora_setup_full6119.exe', 'https://download.wondershare.kr/filmora_full6119.exe'],
    ['FiveKPlayer','5kplayer-setup.exe','https://www.5kplayer.com/download/5kplayer-setup.exe'],
    ['AVG Antivirus Free','avg_antivirus_free_setup.exe','https://www.avg.com/en-us/download-thank-you.php?product=FREEGSR-FAD#pc'],
    ['Turbo Vaccine','TVIS_R3_M.exe','https://www.turbovaccine.com/TVIS_R3_M.exe'],
    ['Avast Free Antivirus','thiết_lập_Avast_Free_Antivirus_trực_tuyến.exe','https://www.avast.com/vi-vn/download-thank-you.php?product=FAV-ONLINE-HP&locale=vi-vn&direct=1'],
    ['Avast Secure Browser', 'avast_secure_browser_setup.exe', 'https://www.softonic.kr/download-launch?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkb3dubG9hZFR5cGUiOiJleHRlcm5hbERvd25sb2FkIiwiZG93bmxvYWRVcmwiOiJodHRwczovL2Nkbi1kb3dubG9hZC5hdmFzdGJyb3dzZXIuY29tL3NvZnRvbmljL2F2YXN0X3NlY3VyZV9icm93c2VyX3NldHVwLmV4ZSIsImFwcElkIjoiYTlhMjJlMzgtYTRkNC0xMWU2LTg5NGMtMDAxNjNlZDgzM2U3IiwicGxhdGZvcm1JZCI6IndpbmRvd3MiLCJpYXQiOjE3NDA5NzI0OTcsImV4cCI6MTc0MDk3NjA5N30.dTKBLZf0jWOD2mnKKuEqTHqA1EoEVMre2qPRZgDmHxY'],
    ['Goclean','gocleansetup152.exe','https://www.gobest.kr/goclean_app/index.htm'],
    ['Rockstar Games Launcher', 'Rockstar-Games-Launcher.exe', 'https://gamedownloads.rockstargames.com/public/installer/Rockstar-Games-Launcher.exe?_gl=1*tyd6fv*_gcl_au*MjQzNTIzNjk3LjE3NDIxMzM0Mjc.*_ga*MjM0NjIzMzA4LjE3NDIxMzM0MDU.*_ga_PJQ2JYZDQC*MTc0MjEzMzQwNC4xLjEuMTc0MjEzMzQ0MS4wLjAuMA..'],
    ['Tom Clancy Rainbow Six Siege', 'UbisoftConnectInstaller.exe', 'https://static3.cdn.ubi.com/orbit/launcher_installer/UbisoftConnectInstaller.exe'],
    ['Google Chrome', 'ChromeSetup.exe', 'https://dl.google.com/tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26iid%3D%7B2EE99883-F8F0-300A-4491-387A047F9582%7D%26lang%3Dvi%26browser%3D4%26usagestats%3D1%26appname%3DGoogle%2520Chrome%26needsadmin%3Dprefers%26ap%3Dx64-statsdef_1%26installdataindex%3Dempty/update2/installers/ChromeSetup.exe'],
    ['Microsoft Edge', 'MicrosoftEdgeSetup.exe', 'https://c2rsetup.officeapps.live.com/c2r/downloadEdge.aspx?platform=Default&source=EdgeStablePage&Channel=Stable&language=vi&brand=M100'],
    ['BAND', 'BAND-1.10.13.exe', 'https://www.band.us/cs/notice/1301'],
    ['Formtec Design Pro 9', 'DesignPro_9_Setup_UP9.exe', 'https://download.formtec.co.kr/download/DesignPro_9_Setup_UP9.exe'],
    ['VirtualDJ', '', 'Microsoft Store'],
    ['Epic Games Store', '', 'Microsoft Store'],
    ['Angry Birds 2', '', 'Microsoft Store'],
    ['Asphalt 8: Airborne', '', 'Microsoft Store'],
    ['Naval Armada: Sea Battle Online', '', 'Microsoft Store'],
    ['Candy Crush Saga', '', 'Microsoft Store'],
    ['Despicable Me: Minion Rush', '', 'Microsoft Store'],
    ['Hidden City: Hidden Object Adventure', '', 'Microsoft Store'],
    ['Homescapes', '', 'Microsoft Store'],
    ['Microsoft Jigsaw', '', 'Microsoft Store'],
    ['Microsoft Mahjong', '', 'Microsoft Store'],
    ['Microsoft Minesweeper', '', 'Microsoft Store'],
    ['Microsoft Solitaire Collection', '', 'Microsoft Store'],
    ['Microsoft Sudoku', '', 'Microsoft Store'],
    ['Minecraft Education', '', 'Microsoft Store'],
    ['SpongeBob: Krusty Cook-Off', '', 'Microsoft Store'],
    ['Township', '', 'Microsoft Store'],
    ['Microsoft Sticky Notes', '', 'Microsoft Store'],
    ['Citrix Workspace App', '', 'Microsoft Store'],
    ['Microsoft copilot 365', '', 'Microsoft Store'],
    ['Power BI Desktop', '', 'Microsoft Store'],
    ['WPS Office UWP', '', 'Microsoft Store'],
    ['Snipping Tool', '', 'Microsoft Store'],
    ['Windows Notepad', '', 'Microsoft Store'],
    ['GOM Player - Free Video Player', '', 'Microsoft Store'],
    ['VLC UWP', '', 'Microsoft Store'],
    ['KakaoTalk', '', 'Microsoft Store'],
    ['Microsoft Teams', '', 'Microsoft Store'],
    ['Skype', '', 'Microsoft Store'],
    ['WhatsApp', '', 'Microsoft Store'],
    ['Brave Browser', '', 'Microsoft Store'],
    ['Mozilla Firefox', '', 'Microsoft Store'],
    ['Discord', '', 'Microsoft Store'],
    ['Audacity', '', 'Microsoft Store'],
    ['Paint', '', 'Microsoft Store'],
    ['Netflix', '', 'Microsoft Store'],
    ['Spirality', '', 'Microsoft Store'],
    ['Pulse Secure', '', 'Microsoft Store'],
    ['Amazon Music', '', 'Microsoft Store'],
    ['Microsoft Clipchamp', '', 'Microsoft Store'],
    ['iTunes', '', 'Microsoft Store'],
    ['Spotify - Music and Podcasts', '', 'Microsoft Store'],
    ['Wondershare Filmora - AI Video Editor', '', 'Microsoft Store'],
    ['Canva', '', 'Microsoft Store'],
    ['Lively Wallpaper', '', 'Microsoft Store'],
    ['TranslucentTB', '', 'Microsoft Store'],
    ['Windows Scan', '', 'Microsoft Store'],
    ['iCloud', '', 'Microsoft Store'],
    ['Inkscape', '', 'Microsoft Store'],
    ['Mail', '', 'Microsoft Store'],
    ['OneNote', '', 'Microsoft Store'],
    ['Neat Office - DOCX & PDF Editor', '', 'Microsoft Store'],
    ['Slack', '', 'Microsoft Store'],
    ['Trio Office: DOCX & XLSX Editor', '', 'Microsoft Store'],
    ['Messenger', '', 'Microsoft Store'],
    ['Pinterest', '', 'Microsoft Store'],
    ['Viber', '', 'Microsoft Store'],
    ['Intel® Graphics Command Center', '', 'Microsoft Store'],
    ['HP Smart', '', 'Microsoft Store'],
    ['Snippet', '', 'Microsoft Store'],
    ['Sway', '', 'Microsoft Store'],
    ['Windows Calculator', '', 'Microsoft Store'],
    ['Windows Scan', '', 'Microsoft Store'],
    ['PhotoScape X', '', 'Microsoft Store'],
    ['Microsoft To Do: Lists, Tasks & Reminders', '', 'Microsoft Store'],
    ['BreeZip: RAR & ZIP Extractor', '', 'Microsoft Store'],
    ['Drawboard PDF - PDF Reader & PDF Editor', '', 'Microsoft Store'],
    ['Cooking Fever', '', 'Microsoft Store'],
    ['Dragon Mania Legends', '', 'Microsoft Store'],
    ['OP Auto Clicker', '', 'Microsoft Store'],
    ['Microsoft PowerToys', '', 'Microsoft Store'],
    ['TikTok', '', 'Microsoft Store'],
    ['Phone Link', '', 'Microsoft Store'],
    ['Windows Notepad', '', 'Microsoft Store'],
    ['Feedback Hub', '', 'Microsoft Store'],
    ['Windows Clock', '', 'Microsoft Store'],
    ['Windows Calculator', '', 'Microsoft Store'],
    ['Microsoft 365 Copilot', '', 'Microsoft Store'],
    ['PDF24 Creator', '', 'Microsoft Store'],
]


# data = [
#     ['Comtime Noti','alrimi_setup.exe','https://comci.kr/download/ilgwa/alrimi_setup.exe'],
#     ['CalendarTask','xdiarys-setup-v3.exe','https://download.xdiarys.com/windows/xdiarys-setup-v3.exe'],
#     ['EditPlus','epp600_0632_64bit.exe','https://www.editplus.com/ftp/epp600_0632_64bit.exe'],
#     ['ezPDF Editor','ezPDFEditor_Personal_Setup_3.0.8.4.exe','https://www.unidocs.co.kr/data/ezpdfeditor/personal/ezPDFEditor_Personal_Setup_3.0.8.4.exe'],
#     ['Foxit PDF','FoxitPDFReader20244_enu_Setup_Prom.exe','https://www.foxit.com/downloads/pdf-reader-thanks.html?product=Foxit-Reader&platform=Windows&version=&package_type=&language=English&formId=download-reader'],
#     ['Libre Office','LibreOffice_25.2.1_Win_x86-64.msi','https://www.libreoffice.org/donate/dl/win-x86_64/25.2.1/ko/LibreOffice_25.2.1_Win_x86-64.msi'],
#     ['Logitech G Hub','lghub_installer.exe','https://download01.logi.com/web/ftp/pub/techsupport/gaming/lghub_installer.exe'],
#     ['Notion','Notion Setup 4.6.0 arm64.exe','https://www.notion.com/desktop/windows-arm/download?from=marketing&pathname=%2Fko%2Fdownload&tid=8ada6209fc324f9a95d58a30115fe3a5'],
#     ['pdf architect 9','PDFArchitectInstaller-p8hbqdpJ.exe','https://www.pdfarchitect.org/download/?config=AF3CEDDA-7E46-429B-A312-C8F312C86063&amp;__hstc=113466648.8868cb281266d00566a6dc3d4b969c84.1741246812268.1741246812268.1741246812268.1&amp;__hssc=113466648.1.1741246812268&amp;__hsfp=2803957637?visitorId=e6865ff0-1a47-4b68-bdbf-f672170964c9&amp;culture=en&amp;referral=www.pdfforge.org%2Fpdfarchitect&amp;ref=pdfforge.org%2Fpdfarchitect&amp;wid=8193&amp;uid=1015225&amp;src=direct&amp;cmp=pdfa_all_o_all_all_all_architect&amp;key1=default&amp;key2=default&amp;keyb=none&amp;mkey1=pdfforge.org%2Fpdfarchitect&amp;mkey2=none&amp;mkey3=none&amp;mkey4=e6865ff0-1a47-4b68-bdbf-f672170964c9&amp;mkey5=none&amp;mkey6=039e4237-4cd2-4055-d20d-969f3dbf9796_2025-03-06&amp;mkey7=none&amp;mkey8=none&amp;mkey9=none&amp;mkey10=none&amp;gclid=none&amp;msclkid=none&amp;fbclid=none&amp;pixa=none&amp;partner=none&amp;qti=039e4237-4cd2-4055-d20d-969f3dbf9796_2025-03-06&amp;cid=1446315843.1741246812'],
#     ['textmaker','','https://www.softmaker.net/down/softmaker-office-nx-64.msi'],
#     ['Thunderbird','','https://download.mozilla.org/?product=thunderbird-136.0-SSL&amp;os=win64&amp;lang=en-US'],
#     ['Zalo','','https://res-download-pc.zadn.vn/win/ZaloSetup-25.2.1.exe'],
#     ['OpenRefine','','https://github.com/OpenRefine/OpenRefine/releases/download/3.9.0/openrefine-win-with-java-3.9.0.zip'],
#     ['Moneydance','','https://infinitekind.com/stabledl/current/Moneydance_windows_amd64.exe'],
#     ['OpenOffice','','https://sourceforge.net/projects/openofficeorg.mirror/files/latest/download'],
#     ['NetBeans','','https://dlcdn.apache.org/netbeans/netbeans-installers/25/Apache-NetBeans-25-bin-windows-x64.exe'],
#     ['OP GG','','https://op.gg/desktop/download/latest'],
#     ['Korean Investment HTS','','https://new.real.download.dws.co.kr/download/eFriendPlus_setup.exe'],
#     ['Java','','https://javadl.oracle.com/webapps/download/AutoDL?BundleId=251656_7ed26d28139143f38c58992680c214a5'],
#     ['Altools','','https://advert.estsoft.com/?event=200910145916818'],
#     ['Avast Cleanup','','https://www.avast.com/download-thank-you.php?product=FAV-ONLINE-STORE&amp;locale=en-ww&amp;direct=1'],
#     ['Binance','','https://download.binance.com/electron-desktop/windows/production/binance-setup.exe'],
#     # ['brother','','https://download.brother.com/welcome/dlf105119/Y20A_C1_ULWC_PP-inst-E1.EXE']
#     ['Everything','','https://www.voidtools.com/Everything-1.4.1.1026.x64-Setup.exe'],
#     ['FileZilla','','https://download.filezilla-project.org/client/FileZilla_3.68.1_win64_sponsored2-setup.exe'],
#     ['Grammarly','','https://download-windows.grammarly.com/w/GrammarlyInstaller.exe?browserName=microsoft%20edge&amp;containerId=olgk9mcgh5n40202&amp;state=gTOAm&amp;_gl=1*19n9kc9*_gcl_au*MTMwOTMzNDA5Ni4xNzQxNzYxOTYw'],
#     ['ipTIME','','http://download.iptime.co.kr/online_upgrade/ipTIME_Upgrade_Noti_Setup_1.36.exe'],
#     ['Kiwoom Hero Gate','','https://download.kiwoom.com/herog_custom/KiwoomGlobalSetup.exe'],
#     ['LD Player','','https://res.ldrescdn.com/download/LDPlayer9.exe?n=LDPlayer9_vn_1003_ld.exe'],
#     ['Lightshot','','http://app.prntscr.com/build/setup-lightshot.exe'],
#     ['Naver eBook Reader','','https://appdown.pstatic.net/naver/pcebookviewer/NBInstaller.exe'],
#     ['MEMU PLAY','','https://www.memuplay.com/download-memu-on-pc.html?from=offline_installer_web'],
#     ['nPDF','','https://github.com/jjkapp/jjkapp.github.io/raw/master/npdf/nPDF_0.9.3.1_(32%2C64bit).exe'],
#     ['RAZER SYNAPSE','','https://rzr.to/synapse-3-pc-download'],
#     ['Turbo Cleaner','','http://up1.turbovaccine.com/Download/TurboCleaner/TurboCleanerSetup.exe'],
#     ['uTorrent_Classic', '', 'https://www.utorrent.com/downloads/complete/track/stable/os/win/'],
#     ['virtualbox headless frontend','','https://download.virtualbox.org/virtualbox/7.1.6/VirtualBox-7.1.6-167084-Win.exe'],
#     ['WinRAR','','https://www.win-rar.com/postdownload.html?&L=0'],
#     ['WinZip','','https://download.winzip.com/gl/nkln/winzip76-home.exe'],
#     ['Double Commander','','https://sourceforge.net/projects/doublecmd/files/latest/download'],
#     ['muCommander','','https://github.com/mucommander/mucommander/releases/download/1.5.2-1/mucommander-1.5.2.msi'],
#     ['Anaconda','','https://repo.anaconda.com/archive/Anaconda3-2024.10-1-Windows-x86_64.exe'],
#     ['Overwolf','','https://download.overwolf.com/install/Download?utm_source=web_app_store']
#                 ]

app_list_data = sorted(data, key=lambda x: x[0])

print(len(app_list_data))